### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by chiragnahata** [MishaTY/Rectify11Installer#94] opened 2023-01-10 10:56 UTC
### Description

I am unable to uninstall rectify 11 installer. Please help as soon as possible. It is not letting me click the uninstall button

### Steps To Reproduce

Install and then  try to uninstall

### Rectify11 Version

3.0 rp3

### Windows Version

Latest

### Logs

![image](https://user-images.githubusercontent.com/63905783/211533209-a5ddd797-8918-41c3-bf57-eeb6395cc135.png)

**Comment by MishaTY** [comment] 2023-01-10 12:17
Duplicate of #71 #89

**Closed by MishaTY** 2023-01-10 12:17 UTC
Labels: bug
