### ISSUE TITLE
Why I can't uninstall it?

### ISSUE THREAD

**Issue by CuibapKhuong** [MishaTy/Rectify11Installer#129] opened 2023-04-08 11:05 UTC
### Description

When I installed it, I wanted to uninstall it, I clicked Uninstall button but nothing happened. I tried so many times but nothing still happened.
- Use System Restore: failed.
- I tried to uninstall / change it from Control Panel: failed.
- Went to C:\Windows\Rectify11\Uninstall.exe: failed.
Don't tell me to reset my PC or sfc /scannow.

### Steps To Reproduce

Step 1: Install Rectify11Installer.exe (99,9MB).
Step 2: You need to click install now.
- Rectified System icons, Themes and Extras.
- Windows 11 Deafult, Extend Mica to explorer navigation bar, Use Enhanced Ribbon.
Wait for it when it is patching files.
Step 3: After the installer, you click Uninstall and you will receive a result: nothing will happen.

### Rectify11 Version

Version: 3.0 rp3

### Windows Version

Windows 11 22H2 22621.1485

### Logs

![image](https://user-images.githubusercontent.com/129703284/230718384-5a3e38e0-7a33-44d5-8db5-57273d9764a5.png)

**Comment by CuibapKhuong** [comment] 2023-04-08 11:07
> ### Description
> When I installed it, I wanted to uninstall it, I clicked Uninstall button but nothing happened. I tried so many times but nothing still happened.
> 
> * Use System Restore: failed.
> * I tried to uninstall / change it from Control Panel: failed.
> * Went to C:\Windows\Rectify11\Uninstall.exe: failed.
>   Don't tell me to reset my PC or sfcc /scannow.
> 
> ### Steps To Reproduce
> Step 1: Install Rectify11Installer.exe (99,9MB). Step 2: You need to click install now.
> 
> * Rectified System icons, Themes and Extras.
> * Windows 11 Deafult, Extend Mica to explorer navigation bar, Use Enhanced Ribbon.
>   Wait for it when it is patching files.
>   Step 3: After the installer, you click Uninstall and you will receive a result: nothing will happen.
> 
> ### Rectify11 Version
> Version: 3.0 rp3
> 
> ### Windows Version
> Windows 11 22H2 22621.1485
> 
> ### Logs
> ![image](https://user-images.githubusercontent.com/129703284/230717825-209efd08-cf7c-468f-9c38-b734dac62424.png)

**Comment by ItsProfessional** [comment] 2023-04-08 11:38
>    Use System Restore: failed.
it should work, I don't know what you mean

>    I tried to uninstall / change it from Control Panel: failed.
obviously, its because the uninstaller has not been implemented yet

>    Went to C:\Windows\Rectify11\Uninstall.exe: failed.
thats the same thing as the control panel

>    Don't tell me to reset my PC or sfc /scannow.
sfc /scannow will not mess up windows, or delete anything. you can use it
if not, you have to wait for the developer to implement the uninstaller

**Comment by MishaTy** [comment] 2023-04-08 12:00
Duplicate of #99 #94 #89 #71

**Closed by MishaTy** 2023-04-08 12:00 UTC
Labels: bug

**Comment by evansidhu** [comment] 2023-05-31 19:37
System restore via windows recovery environment works
